
var firstname = "Debashish jena";
var age="     AGE:";
var number="21";
var gender="     GENDER:";
var types="MALE";
console.log( firstname +" "+age+" "+number+" "+gender+" "+types);
var subject = "ENGLISH     : ";
var mark = "80";
var total = subject + mark;
console.log(total);
var subject = "PHYSICS     : ";
var mark = "75";
var total = subject + mark;
console.log(total);
var subject = "MATH        : ";
var mark = "62";
var total = subject + mark;
console.log(total);
var subject = "CHEMISTRY   : ";
var mark = "95";
var total = subject + mark;
console.log(total);
var subject = "BIOLOGY     : ";
var mark = "78";
var total = subject + mark;
console.log(total);
var subject = "HINDI       : "
var mark = "83";
var total = subject + mark;
console.log(total);
var sum = "      TOTAL : ";
var total = 80 + 75 + 62 + 95 + 78 + 83;
var mark = sum + total;
console.log(mark);
var average = "      AVG : ";
var avg = total / 6;
var last = average + avg;
console.log(last);
var firstname = "ASISH KUMAR JENA";
var age="     AGE:";
var number="19";
var gender="     GENDER:";
var types="MALE";
console.log( firstname +" "+age+" "+number+" "+gender+" "+types);
var subject = "ENGLISH     : ";
var mark = "57";
var total = subject + mark;
console.log(total);
var subject = "PHYSICS     : ";
var mark = "93";
var total = subject + mark;
console.log(total);
var subject = "MATH        : ";
var mark = "65";
var total = subject + mark;
console.log(total);
var subject = "CHEMISTRY   : ";
var mark = "78";
var total = subject + mark;
console.log(total);
var subject = "IT          : ";
var mark = "83";
var total = subject + mark;
console.log(total);
var subject = "HINDI       : ";
var mark = "59";
var total = subject + mark;
console.log(total);
var sum = "      TOTAL : ";
var total = 59 + 83 + 78 + 65 + 93 + 57;
var avg = sum + total;
console.log(avg);
var sum = "      AVG : ";
var average = total / 6;
console.log(sum + average);
var firstname = "AKASH JENA";
var age="     AGE:";
var number="20";
var gender="     GENDER:";
var types="MALE";
console.log( firstname +" "+age+" "+number+" "+gender+" "+types);
var subject="ENGLISH     : ";
var mark="67";
console.log(subject+mark);
var subject="PHYSICS     : ";
var mark="59";
console.log(subject+mark);
var subject="MATH        : ";
var mark="82";
console.log(subject+mark);
var subject="CHEMISTRY   : ";
var mark="68";
console.log(subject+mark);
var subject="IT          : ";
var mark="96";
console.log(subject+mark);
var subject="SANSKRIT    : ";
var mark="79";
console.log(subject+mark);
var total="      TOTAL : ";
var mark=79+96+68+82+59+67;
console.log(total+mark);
var average="      AVG : ";
var final=mark/6;
console.log(average+final);
var firstname="MANAS RANJAN JENA";
var age="     AGE:";
var number="28";
var gender="     GENDER:";
var types="MALE";
console.log( firstname +" "+age+" "+number+" "+gender+" "+types);
var subject="ENGLISH     : ";
var mark="89";
console.log(subject+mark);
var subject="PHYSICS     : ";
var mark="68";
console.log(subject+mark);
var subject="MATH        : ";
var mark="89";
console.log(subject+mark);
var subject="CHEMISTRY   : ";
var mark="75";
console.log(subject+mark);
var subject="IT          : ";
var mark="82";
console.log(subject+mark);
var subject="HINDI       : ";
var mark="83";
console.log(subject+mark);
var sum="      TOTAL : ";
var add=83+82+75+89+68+89;
console.log(sum+add);
var average="      AVG : ";
var final=add/6;
console.log(average+final);
var firstname="BIKASH KUMAR JENA";
var age="     AGE:";
var number="22";
var gender="     GENDER:";
var types="MALE";
console.log( firstname +" "+age+" "+number+" "+gender+" "+types);
var subject="ENGLISH     : ";
var mark="58";
console.log(subject+mark);
var subject="PHYSICS     : ";
var mark="92";
console.log(subject+mark);
var subject="MATH        : ";
var mark="95";
console.log(subject+mark);
var subject="CHEMISTRY   : ";
var mark="79";
console.log(subject+mark);
var subject="IT          : ";
var mark="87";
console.log(subject+mark);
var subject="ODIA        : ";
var mark="67";
console.log(subject+mark);
var total="      TOTAL : "
var sum=67+87+79+95+92+58;
console.log(total+sum);
var average="      AVG : ";
var last=sum/6;
console.log(average+last);