var c="SORT";
console.log(c);
var a =["Jitendra","Debashish","siba"];
console.log(a);
a.sort();
console.log(a);
var b =[25,68,92,67];
console.log(b);
b.sort();
console.log(b);
var d="REVERSE";
console.log(d);
var a=[22,54,65,94];
console.log(a);
a.reverse();
console.log(a);
var b =["Sagar","Deba","Amar"];
console.log(b);
b.reverse();
console.log(b);